name: pr-loop

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "hotfix" ]
jobs:
  pr-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run e2e pipeline test
        run: ./pb.ps1
        shell: pwsh
