name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number to download artifact from'
        required: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ./artifacts
        run-id: ${{ github.event.inputs.build_number }}
